name: ALIEN 4 Cloud Documentation Portal
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highligter: pygments
encoding: UTF-8

categories-list: ["DOCUMENTATION", "DOCUMENTATION-1.1.0", "RELEASE_NOTES", "DEVELOPER_GUIDE", "ROADMAP"]

last-version: "1.1.0-SM6"
last-snapshot: "1.1.0-SM7-SNAPSHOT"
pullrequesturl: http://prose.io/#alien4cloud/alien4cloud.github.io/edit/sources/
